"""esquema inicial de pecas, caixas e auditoria

Revision ID: 25c56a8ef65f
Revises: 
Create Date: 2026-09-22 22:49:11.297648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c56a8ef65f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=32), nullable=False),
    sa.Column('entidade', sa.String(length=32), nullable=False),
    sa.Column('entidade_id', sa.String(length=64), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_criada_em'), ['criada_em'], unique=False)

    op.create_table('caixas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('ABERTA', 'FECHADA')", name='ck_caixa_status'),
    sa.CheckConstraint('capacidade = 10', name='ck_caixa_capacidade'),
    sa.CheckConstraint('quantidade >= 0 AND quantidade <= capacidade', name='ck_caixa_quantidade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caixas_status'), ['status'], unique=False)

    op.create_table('pecas',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('peso', sa.String(length=32), nullable=False),
    sa.Column('cor', sa.String(length=32), nullable=False),
    sa.Column('comprimento', sa.String(length=32), nullable=False),
    sa.Column('resultado', sa.String(length=16), nullable=False),
    sa.Column('cadastrada_em', sa.DateTime(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("resultado IN ('APROVADA', 'REPROVADA')", name='ck_peca_resultado'),
    sa.CheckConstraint('comprimento > 0', name='ck_peca_comprimento'),
    sa.CheckConstraint('peso > 0', name='ck_peca_peso'),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('codigo')
    )
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pecas_cadastrada_em'), ['cadastrada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pecas_caixa_id'), ['caixa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pecas_cor'), ['cor'], unique=False)
        batch_op.create_index(batch_op.f('ix_pecas_resultado'), ['resultado'], unique=False)

    op.create_table('motivos_reprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_codigo', sa.String(length=32), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=False),
    sa.CheckConstraint("descricao IN ('Peso abaixo do permitido', 'Peso acima do permitido', 'Cor não permitida', 'Comprimento abaixo do permitido', 'Comprimento acima do permitido')", name='ck_motivo_descricao'),
    sa.ForeignKeyConstraint(['peca_codigo'], ['pecas.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motivos_reprovacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motivos_reprovacao_peca_codigo'), ['peca_codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motivos_reprovacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motivos_reprovacao_peca_codigo'))

    op.drop_table('motivos_reprovacao')
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pecas_resultado'))
        batch_op.drop_index(batch_op.f('ix_pecas_cor'))
        batch_op.drop_index(batch_op.f('ix_pecas_caixa_id'))
        batch_op.drop_index(batch_op.f('ix_pecas_cadastrada_em'))

    op.drop_table('pecas')
    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caixas_status'))

    op.drop_table('caixas')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_criada_em'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
